language: cpp
env:
	- BUILD_TYPE=Release
	- BUILD_TYPE=Debug
	- TOOLCHAIN=bebop BUILD_TYPE=Release
	- TOOLCHAIN=bebop BUILD_TYPE=Debug
before_script:
	- mkdir build && cd build
	- cmake ../ -DCMAKE_TOOLCHAIN_FILE=toolchains/$TOOLCHAIN-toochain.cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE
script:
	- make -j2
